name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]  # [3.6, 3.7, 3.8, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install black codespell flake8 isort pytest
      - run: black --check .
      - run: codespell --quiet-level=2  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --max-line-length=88 --show-source --statistics
      - run: isort --profile black .
      - run: pip install -r requirements.txt || true
      - run: pytest . || true
